import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' className='max-w-7xl mx-auto px-4 bg-blue-950 '>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className='py-4 bg-blue-950 opacity-45 text-yellow-200 font-semibold flex gap-6 justify-center h-16'>
          <ul className='flex gap-4'>
            <li>
              <Link href='/'>Home</Link>
            </li>
            |
            <li>
              <Link href='/about'>About</Link>
            </li>
          </ul>{' '}
        </nav>

        <div className='h-[90vh] bg-blue-950 '>{children}</div>
        <footer className='h-20'></footer>
      </body>
    </html>
  );
}
